batch_size: 64
data_params:
  bg_color:
    maxs:
    - - 1.0
      - 1.0
      - 1.0
    - - 0.0
      - 0.0
      - 0.0
    means:
    - - 1.0
      - 1.0
      - 1.0
    - - 0.0
      - 0.0
      - 0.0
    mins:
    - - 1.0
      - 1.0
      - 1.0
    - - 0.0
      - 0.0
      - 0.0
    s_n: 0.0
  color:
    maxs:
    - - 1.0
      - 0.2
      - 0.2
    - - 0.2
      - 0.2
      - 1.0
    means:
    - - 0.9
      - 0.1
      - 0.1
    - - 0.1
      - 0.1
      - 0.9
    mins:
    - - 0.8
      - 0.0
      - 0.0
    - - 0.0
      - 0.0
      - 0.8
    s_n: 0.0
  comp_dims:
    bg_color: null
    color: 2
    shape: 2
    size: 2
    x: null
    y: null
  image_size: 28
  n_classes: 8
  noise_level: 0.001
  shape:
    names:
    - circle
    - triangle
  size:
    maxs:
    - 0.65
    - 0.45
    means:
    - 0.6
    - 0.4
    min: 0.1
    mins:
    - 0.55
    - 0.4
    s_n: 0.0
  x:
    max: 0.0
    min: 0.0
    n: null
    s: 0.0
    s_n: 0.0
  y:
    max: 0.0
    min: 0.0
    n: null
    s: 0.0
    s_n: 0.0
dataset: images_1
experiment_directory: data/images_1/2x2x2_final/sc2ss2sb2_re/shape_color_size/seed=100
fig_n_col: 4
model_params:
  beta_settings:
    gamma_max: 10.0
    gamma_min: -5.0
    noise_schedule: learned_linear
    type: logsnr
  data_noise: 0.001
  model_type: VDiff
  network_params:
    chs:
    - 64
    - 128
    - 256
    init_scale: 1.0
    mid_attn: true
    num_res_blocks: 2
    v_conditioning_dims:
    - 11
    v_conditioning_type: sep_mlp
  optimizer_params:
    lr: 0.001
    weight_decay: 0.01
  optimizer_type: AdamW
n_samples_test:
- 0
- 0
- 0
- 2048
- 0
- 2048
- 2048
- 2048
n_samples_test_gen:
- 0
- 0
- 0
- 1024
- 0
- 1024
- 1024
- 1024
n_samples_train:
- 2048
- 2048
- 2048
- 0
- 2048
- 0
- 0
- 0
n_samples_train_gen:
- 1024
- 1024
- 1024
- 0
- 1024
- 0
- 0
- 0
num_steps: 40000
save_steps: 120
save_steps_start: 50
seed: 100
train_ratio: 0.85
